CREATE TABLE IF NOT EXISTS customers
(
    id           INTEGER PRIMARY KEY,
    email        CHARACTER VARYING(255) NOT NULL,
    password     CHARACTER VARYING(255) NOT NULL,
    status       CHARACTER VARYING(20) NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version      BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS card_links
(
    id            CHARACTER VARYING(255) PRIMARY KEY,
    user_id       INTEGER NOT NULL,
    ext_card_id   CHARACTER VARYING(255),
    masked_pan    CHARACTER VARYING(255),
    status        CHARACTER VARYING(20) NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    version       BIGINT NOT NULL
);
